name: square_camera
description: A new Flutter plugin.
version: 0.0.1
homepage: https://github.com/dev-juyoung/flutter-square-camera

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2
  camera: ^0.5.8+11
  path: ^1.7.0
  path_provider: ^1.6.24
  image: ^2.1.19
  image_gallery_saver: ^1.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.juyoung.square.camera
        pluginClass: SquareCameraPlugin
      ios:
        pluginClass: SquareCameraPlugin
